"use client";

import { useCallback, useEffect, useState } from "react";
import { INDIVIDUAL_AREAS, type IndividualArea } from "@/lib/individual-lessons";
import { createClient } from "@/lib/supabase/client";

type Preference = { weekday: number | null; specific_date: string | null; start_time: string; rank: number };
type Application = { id: string; name: string; email: string; phone: string; area: IndividualArea; experience: string | null; alternative_time_request: string | null; requested_sessions_per_week: number; status: string; preferences: Preference[] };
type Booking = { id: string; area: IndividualArea; duration_minutes: number; meeting_link: string; status: string; student: { full_name: string; email: string }; slots: Array<{ weekday: number; start_time: string }> };
type Course = { id: string; title: string; weekly_schedule: Array<{ enabled: boolean; time: string }> | null };
const DAYS = ["Måndag", "Tisdag", "Onsdag", "Torsdag", "Fredag", "Lördag", "Söndag"];
const today = new Date().toISOString().slice(0, 10);

export default function IndividuellaPage() {
  const [applications, setApplications] = useState<Application[]>([]);
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [courses, setCourses] = useState<Course[]>([]);
  const [selected, setSelected] = useState<Application | null>(null);
  const [form, setForm] = useState({ duration_minutes: "60", buffer_minutes: "5", starts_on: today, meeting_link: "", slots: [] as Array<{ weekday: number; start_time: string }> });
  const [message, setMessage] = useState("");
  const [isAdmin, setIsAdmin] = useState(false); const [teachers, setTeachers] = useState<Array<{id:string;full_name:string}>>([]); const [teacherId, setTeacherId] = useState("");
  const [manual, setManual] = useState({ name:"", email:"", phone:"", area:"quran_reading" as IndividualArea });
  const load = useCallback(async () => { const query = teacherId ? `?teacher_id=${teacherId}` : ""; const r = await fetch(`/api/teacher/individual${query}`, { cache: "no-store" }); if (r.ok) { const d = await r.json(); setApplications(d.applications); setBookings(d.bookings); setCourses(d.courses); } }, [teacherId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const supabase=createClient(); supabase.auth.getUser().then(async({data:{user}})=>{ if(!user)return; const {data}=await supabase.from("profiles").select("role").eq("id",user.id).single(); if(data?.role==="admin"){setIsAdmin(true); fetch("/api/admin/students").then(r=>r.json()).then((rows:Array<{id:string;full_name:string;role:string}>)=>setTeachers(rows.filter(x=>x.role==="teacher")));} }); }, []);
  function choose(app: Application) { const prefs = [...(app.preferences ?? [])].sort((a,b) => a.rank-b.rank).filter(p => p.weekday).slice(0, app.requested_sessions_per_week).map(p => ({ weekday: p.weekday!, start_time: p.start_time.slice(0,5) })); setSelected(app); setForm({ duration_minutes: "60", buffer_minutes: "5", starts_on: today, meeting_link: "", slots: prefs }); setMessage(""); }
  async function decide(status: "approved" | "rejected") { if (!selected) return; const r = await fetch("/api/teacher/individual", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: selected.id, status, ...form }) }); const d = await r.json(); setMessage(r.ok ? (status === "approved" ? "Eleven är bokad och har fått ett mejl." : "Ansökan har avslagits.") : d.error); if (r.ok) { setSelected(null); void load(); } }
  async function editBooking(booking: Booking) { const meeting_link = window.prompt("Ny möteslänk", booking.meeting_link); if (!meeting_link || meeting_link === booking.meeting_link) return; const r = await fetch("/api/teacher/individual", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: booking.id, meeting_link }) }); const d = await r.json(); setMessage(r.ok ? "Möteslänken har uppdaterats överallt." : d.error); if (r.ok) void load(); }
  async function changeOccurrence(booking: Booking) { const original_date=window.prompt("Datumet som ska ändras (ÅÅÅÅ-MM-DD)"); if(!original_date)return; const replacement=window.prompt("Ny tid (ÅÅÅÅ-MM-DD HH:MM), eller lämna tomt för att ställa in lektionen"); const replacement_start=replacement?new Date(replacement.replace(" ","T")):null; const r=await fetch("/api/teacher/individual",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:booking.id,original_date,exception_status:replacement?"rescheduled":"cancelled",replacement_start:replacement_start?.toISOString()})}); const d=await r.json(); setMessage(r.ok?"Avvikelsen är sparad och visas i elevens schema.":d.error); }
  async function createManual(e: React.FormEvent) { e.preventDefault(); const r=await fetch("/api/admin/individual",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...manual,teacher_id:teacherId})}); const d=await r.json(); setMessage(r.ok?"Ansökan skapades. Öppna den nedan och boka tiderna.":d.error); if(r.ok){setManual({name:"",email:"",phone:"",area:"quran_reading"});void load();} }
  function updateSlot(index: number, key: "weekday"|"start_time", value: string) { setForm(f => ({ ...f, slots: f.slots.map((s,i) => i === index ? { ...s, [key]: key === "weekday" ? Number(value) : value } : s) })); }
  return <div className="max-w-6xl space-y-6"><div><h1 className="text-2xl font-bold">Individuella lektioner</h1><p className="text-sm text-gray-500 mt-1">Granska ansökningar och se alla återkommande individuella bokningar.</p></div>{message && <div className="bg-amber-50 rounded-xl p-4 text-sm">{message}</div>}
    {isAdmin&&<><section className="bg-white rounded-2xl border p-5"><label className="text-sm font-semibold">Hantera lärare<select className="ml-3 border rounded-lg p-2" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Välj lärare</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label></section>{teacherId&&<form onSubmit={createManual} className="bg-white rounded-2xl border p-5 space-y-3"><h2 className="font-semibold">Boka elev manuellt</h2><p className="text-xs text-gray-500">Skapa först eleven som en ansökan och välj sedan tider, längd och möteslänk i granskningsrutan.</p><div className="grid sm:grid-cols-4 gap-3"><input required className="border rounded-lg p-2" placeholder="Namn" value={manual.name} onChange={e=>setManual({...manual,name:e.target.value})}/><input required type="email" className="border rounded-lg p-2" placeholder="E-post" value={manual.email} onChange={e=>setManual({...manual,email:e.target.value})}/><input className="border rounded-lg p-2" placeholder="Telefon" value={manual.phone} onChange={e=>setManual({...manual,phone:e.target.value})}/><select className="border rounded-lg p-2" value={manual.area} onChange={e=>setManual({...manual,area:e.target.value as IndividualArea})}>{Object.entries(INDIVIDUAL_AREAS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><button className="rounded-lg px-4 py-2 text-white text-sm font-semibold" style={{background:"var(--primary)"}}>Skapa för bokning</button></form>}</>}
    <section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-semibold">Väntande ansökningar</h2></div>{applications.filter(a=>a.status==="pending").length === 0 ? <p className="p-6 text-sm text-gray-400">Inga ansökningar väntar.</p> : <div className="divide-y">{applications.filter(a=>a.status==="pending").map(a => <button onClick={() => choose(a)} key={a.id} className="w-full p-5 text-left hover:bg-gray-50 flex justify-between gap-4"><div><p className="font-semibold">{a.name}</p><p className="text-sm text-gray-500">{INDIVIDUAL_AREAS[a.area]} · {a.email} · {a.phone}</p><p className="text-sm mt-2">{a.preferences?.map(p => p.weekday ? `${DAYS[p.weekday-1]} ${p.start_time.slice(0,5)}` : `${p.specific_date} ${p.start_time.slice(0,5)}`).join(" · ") || "Har bett om annan tid"}</p></div><span className="text-sm text-primary">Granska →</span></button>)}</div>}</section>
    {selected && <section className="bg-white rounded-2xl border p-6 space-y-5"><div><h2 className="font-semibold text-lg">Godkänn {selected.name}</h2><p className="text-sm text-gray-500">{selected.experience || "Ingen tidigare erfarenhet angiven."}</p>{selected.alternative_time_request && <p className="mt-2 text-sm bg-gray-50 p-3 rounded-lg"><b>Önskemål:</b> {selected.alternative_time_request}</p>}</div><div className="grid sm:grid-cols-4 gap-3"><label className="text-sm">Längd<input type="number" className="mt-1 border rounded-lg p-2 w-full" value={form.duration_minutes} onChange={e=>setForm({...form,duration_minutes:e.target.value})}/></label><label className="text-sm">Paus<input type="number" className="mt-1 border rounded-lg p-2 w-full" value={form.buffer_minutes} onChange={e=>setForm({...form,buffer_minutes:e.target.value})}/></label><label className="text-sm">Startdatum<input type="date" className="mt-1 border rounded-lg p-2 w-full" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/></label><label className="text-sm">Möteslänk<input type="url" required className="mt-1 border rounded-lg p-2 w-full" placeholder="https://..." value={form.meeting_link} onChange={e=>setForm({...form,meeting_link:e.target.value})}/></label></div><div className="space-y-2"><p className="text-sm font-semibold">Återkommande lektioner per vecka</p>{form.slots.map((s,i)=><div className="flex gap-2" key={i}><select className="border rounded-lg p-2" value={s.weekday} onChange={e=>updateSlot(i,"weekday",e.target.value)}>{DAYS.map((d,n)=><option key={d} value={n+1}>{d}</option>)}</select><input type="time" className="border rounded-lg p-2" value={s.start_time} onChange={e=>updateSlot(i,"start_time",e.target.value)}/><button className="text-red-600 text-sm" onClick={()=>setForm(f=>({...f,slots:f.slots.filter((_,n)=>n!==i)}))}>Ta bort</button></div>)}<button className="text-sm text-primary" onClick={()=>setForm(f=>({...f,slots:[...f.slots,{weekday:1,start_time:"09:00"}]}))}>+ Lägg till lektion</button></div><div className="flex gap-3"><button onClick={()=>void decide("approved")} className="rounded-lg px-5 py-2 text-white font-semibold" style={{background:"var(--primary)"}}>Godkänn och boka</button><button onClick={()=>void decide("rejected")} className="rounded-lg border px-5 py-2 text-red-600">Avslå</button><button onClick={()=>setSelected(null)} className="ml-auto text-gray-500">Stäng</button></div></section>}
    <section className="bg-white rounded-2xl border overflow-hidden"><div className="p-5 border-b"><h2 className="font-semibold">Aktiva bokningar</h2></div>{bookings.length===0?<p className="p-6 text-sm text-gray-400">Inga individuella lektioner är bokade.</p>:<div className="divide-y">{bookings.map(b=><div key={b.id} className="p-5 flex flex-wrap justify-between gap-4"><div><p className="font-semibold">{b.student?.full_name}</p><p className="text-sm text-gray-500">{INDIVIDUAL_AREAS[b.area]} · {b.duration_minutes} min</p><p className="text-sm mt-1">{b.slots?.map(s=>`${DAYS[s.weekday-1]} ${s.start_time.slice(0,5)}`).join(" · ")}</p></div><div className="flex gap-3"><a href={b.meeting_link} target="_blank" rel="noreferrer" className="text-sm text-primary">Öppna länk</a><button onClick={()=>void editBooking(b)} className="text-sm text-gray-600 underline">Ändra länk</button><button onClick={()=>void changeOccurrence(b)} className="text-sm text-gray-600 underline">Omboka/ställ in</button></div></div>)}</div>}</section>
    <section className="bg-white rounded-2xl border p-5"><h2 className="font-semibold mb-4">Samlat veckoschema</h2><div className="grid md:grid-cols-2 gap-3">{courses.flatMap(c=>(c.weekly_schedule??[]).map((s,i)=>s?.enabled?{key:`g-${c.id}-${i}`,day:i+1,time:s.time,title:c.title,type:"Grupp"}:null).filter(Boolean)).concat(bookings.flatMap(b=>(b.slots??[]).map(s=>({key:`i-${b.id}-${s.weekday}-${s.start_time}`,day:s.weekday,time:s.start_time,title:b.student?.full_name,type:"Individuell"})))).sort((a,b)=>(a!.day-b!.day)||a!.time.localeCompare(b!.time)).map(item=><div key={item!.key} className="border rounded-xl p-3"><p className="text-xs text-gray-400">{item!.type}</p><p className="font-medium">{DAYS[item!.day-1]} {item!.time.slice(0,5)}</p><p className="text-sm text-gray-500">{item!.title}</p></div>)}</div></section>
  </div>;
}
