import type { ProgramContent } from "@/components/ProgramDetailPage";

const commonPrice = ["FREE Trial & Assessment Lesson", "10 Live One-to-One Lessons", "Personalized Study Plan", "Qualified Teacher", "Flexible Lesson Scheduling", "Progress Tracking & Teacher Feedback"];

export const quranReading: ProgramContent = {
  eyebrow: "Quran Program",
  title: "Learn to Read the Quran with Confidence",
  intro: "Whether you are taking your first steps or looking to improve your Quran reading, our personalized one-to-one program helps you build a strong foundation through a structured and enjoyable learning journey.",
  assessment: "Every student begins with a FREE trial lesson, where we assess your current level and create a personalized learning plan tailored specifically to your needs.",
  overviewTitle: "A Personalized Learning Experience",
  overview: ["Every student learns differently. Some are complete beginners, while others simply want to improve their fluency and confidence when reading the Holy Quran.", "For this reason, every student begins with a free assessment lesson. During this session, your teacher evaluates your current level and creates a personalized learning plan based on your goals, learning pace, and availability.", "All lessons are delivered live in one-to-one online sessions, ensuring personal attention, continuous guidance, and steady progress throughout your learning journey."],
  benefits: [
    { title: "Personal Learning Plan", text: "Every student follows a customized program designed around their individual needs." },
    { title: "Qualified Teachers", text: "Learn with experienced Quran instructors who provide clear guidance and continuous support." },
    { title: "Flexible Schedule", text: "Choose lesson times that fit comfortably around your daily routine." },
    { title: "One-to-One Classes", text: "Receive individual attention in every lesson to maximize your progress." },
  ],
  learning: [
    { title: "Arabic Alphabet", text: "Learn every Arabic letter from the beginning with clear explanations and step-by-step practice until you recognize and pronounce each letter confidently." },
    { title: "Correct Pronunciation", text: "Develop accurate pronunciation through continuous guidance from your teacher and practical exercises during every lesson." },
    { title: "Reading Fluency", text: "Improve your ability to read words and verses smoothly while building confidence and reducing hesitation." },
    { title: "Quran Reading Skills", text: "Practice reading authentic Quranic verses while gradually developing proper reading habits and accuracy." },
    { title: "Personal Guidance", text: "Receive one-to-one support, continuous corrections, and personalized feedback throughout your learning journey." },
    { title: "Steady Progress", text: "Follow a personalized study plan with regular assessments to ensure continuous improvement and measurable progress." },
  ],
  steps: [
    { title: "Book a Free Trial", text: "Schedule your free online lesson at a time that suits you." },
    { title: "Level Assessment", text: "Your teacher evaluates your current reading level and learning needs." },
    { title: "Personal Study Plan", text: "Receive a customized study plan designed specifically for your goals and pace." },
    { title: "Start Learning", text: "Begin your one-to-one online lessons with continuous support and regular progress tracking." },
  ],
  schedule: "There is no fixed number of lessons per week. Every student follows a personalized schedule based on their goals, current level, and availability. After your free assessment lesson, your teacher will recommend a study plan that allows you to progress comfortably and consistently.",
  price: "$100 / 10 Lessons",
  priceFeatures: [...commonPrice, "Suitable for Children & Adults"],
  reasons: [
    { title: "Qualified Teachers", text: "Learn with experienced Quran teachers dedicated to helping you improve your recitation and reading skills." },
    { title: "One-to-One Lessons", text: "Every lesson is taught individually, allowing your teacher to focus entirely on your learning and progress." },
    { title: "Flexible Scheduling", text: "Choose lesson times that fit your daily routine and study comfortably from anywhere in the world." },
    { title: "Personalized Study Plan", text: "Every student receives a customized learning plan based on their level, goals, and learning pace." },
    { title: "Learn from Anywhere", text: "Join your lessons online from the comfort of your home using your computer, tablet, or smartphone." },
    { title: "Continuous Progress", text: "Regular feedback, progress tracking, and ongoing support help you stay motivated throughout your learning journey." },
  ],
  faqs: [
    { q: "Do I need any previous experience?", a: "No. This program is suitable for complete beginners as well as students who want to improve their Quran reading skills." },
    { q: "How long is each lesson?", a: "Each lesson lasts approximately 45–60 minutes, depending on the student's age and personalized learning plan." },
    { q: "Can children join this program?", a: "Yes. Our Quran Reading Program is designed for both children and adults, with teaching methods adapted to each student's age and level." },
    { q: "What happens after the free trial lesson?", a: "Your teacher will assess your current level, discuss your goals, and recommend a personalized study plan along with a suitable lesson schedule." },
    { q: "How many lessons should I take each week?", a: "There is no fixed number. Your teacher will recommend the ideal weekly schedule based on your level, availability, and learning goals." },
  ],
  ctaTitle: "Ready to Start Your Quran Journey?",
  ctaText: "Take your first step toward reading the Quran with confidence. Book your free trial lesson today, meet your teacher, and receive a personalized learning plan designed just for you.",
};

export const tajweed: ProgramContent = {
  eyebrow: "Tajweed Program",
  title: "Master the Rules of Quran Recitation",
  intro: "Take your Quran recitation to the next level by learning the authentic rules of Tajweed with experienced instructors. Our personalized one-to-one online lessons help you recite the Quran correctly, beautifully, and with confidence.",
  assessment: "Every student begins with a FREE trial lesson, where we assess your current level, identify areas for improvement, and create a personalized learning plan tailored to your goals.",
  overviewTitle: "Master the Science of Tajweed",
  overview: ["Tajweed is the science of reciting the Quran as it was revealed. Through this personalized program, you will learn the essential rules of correct pronunciation and develop the confidence to recite the Quran with clarity and precision.", "Every student begins with a free assessment lesson. During this session, your teacher evaluates your current level, identifies areas for improvement, and creates a personalized study plan based on your learning goals and pace.", "Lessons are delivered live in one-to-one online sessions, providing continuous guidance, practical correction, and regular feedback throughout your learning journey."],
  benefits: [
    { title: "Personal Learning Plan", text: "A customized Tajweed program designed around your current level and personal goals." },
    { title: "Experienced Teachers", text: "Learn with qualified Quran teachers who specialize in Tajweed and proper recitation." },
    { title: "Practical Correction", text: "Receive live correction and immediate feedback during every lesson to improve your recitation." },
    { title: "One-to-One Classes", text: "Benefit from individual attention and a flexible lesson schedule that suits your lifestyle." },
  ],
  learning: [
    { title: "Makharij", text: "Learn the correct articulation points of every Arabic letter to improve pronunciation and achieve accurate Quran recitation." },
    { title: "Sifaat Al-Huroof", text: "Understand the characteristics of Arabic letters and how they affect pronunciation and recitation." },
    { title: "Rules of Tajweed", text: "Study essential rules, including Noon Sakinah, Meem Sakinah, Qalqalah, Ghunnah, and Madd rules." },
    { title: "Practical Application", text: "Apply Tajweed rules while reciting Quranic verses with continuous correction from your teacher." },
    { title: "Personal Feedback", text: "Receive live correction and personalized guidance during every lesson to strengthen your recitation." },
    { title: "Continuous Improvement", text: "Track your progress through regular assessments and gradually develop confidence in your Quran recitation." },
  ],
  steps: [
    { title: "Free Assessment", text: "Your teacher evaluates your current Tajweed level and discusses your learning goals." },
    { title: "Personal Study Plan", text: "We create a personalized Tajweed plan focused on your strengths and areas for improvement." },
    { title: "Live One-to-One Lessons", text: "Attend live lessons with an experienced teacher who provides practical guidance and immediate correction." },
    { title: "Continuous Progress", text: "Develop your recitation through regular practice, teacher feedback, and ongoing assessments." },
  ],
  schedule: "There are no fixed weekly lesson times. During your free assessment, your teacher will recommend the most suitable schedule based on your current level, learning goals, and availability. This personalized approach ensures that every student progresses at a comfortable and effective pace.",
  price: "$100 / 10 Lessons",
  priceFeatures: [...commonPrice, "Practical Tajweed Correction"],
  reasons: [
    { title: "Qualified Teachers", text: "Learn from experienced Quran teachers who specialize in Tajweed and provide clear, practical guidance." },
    { title: "Personalized Learning", text: "Every student follows a customized study plan based on their level, goals, and pace." },
    { title: "One-to-One Lessons", text: "Receive individual attention and instant correction during live online sessions." },
    { title: "Flexible Scheduling", text: "Choose lesson times that fit your work, school, or family commitments." },
    { title: "Progress Tracking", text: "Regular assessments and teacher feedback help you monitor improvement and stay motivated." },
    { title: "Accessible Worldwide", text: "Join online classes from anywhere in the world and study from the comfort of your home." },
  ],
  faqs: [
    { q: "Do I need prior knowledge of Tajweed?", a: "No. The program is suitable for beginners as well as students who want to improve their existing Tajweed skills." },
    { q: "How long is each lesson?", a: "Lesson duration depends on the package you choose and your personalized learning plan. Your teacher will discuss this during the free assessment." },
    { q: "Will I receive individual feedback?", a: "Yes. Every lesson includes live correction and personalized feedback to help you improve your pronunciation and recitation." },
    { q: "Can I choose my lesson schedule?", a: "Yes. We offer flexible scheduling to fit your availability. Your teacher will help you create a suitable timetable after the assessment." },
    { q: "How do I get started?", a: "Simply book your free trial lesson. We'll assess your level, discuss your goals, and prepare a personalized study plan for you." },
  ],
  ctaTitle: "Start Your Tajweed Journey Today",
  ctaText: "Whether you're learning Tajweed for the first time or looking to perfect your Quran recitation, our experienced teachers are here to guide you every step of the way.",
};

export const memorization: ProgramContent = {
  eyebrow: "Quran Memorization Program",
  title: "Memorize the Quran with Confidence and Consistency",
  intro: "Whether you are beginning your Hifz journey or continuing from where you left off, our personalized one-to-one online program helps you memorize the Quran with confidence, accuracy, and long-term retention.",
  assessment: "Every student starts with a FREE trial lesson, where we assess your memorization level, discuss your goals, and create a personalized Hifz plan that fits your pace and schedule.",
  overviewTitle: "Build a Strong and Lasting Hifz Journey",
  overview: ["Memorizing the Quran is a lifelong achievement that requires consistency, encouragement, and the right guidance. Our Quran Memorization Program helps students memorize step by step while maintaining accuracy and confidence.", "Every student begins with a free assessment lesson where we evaluate their current memorization level, discuss their goals, and create a personalized Hifz plan that matches their pace and daily schedule.", "Our experienced teachers guide students through new memorization, regular revision, and continuous evaluation to help strengthen retention and build long-term consistency."],
  benefits: [
    { title: "Personalized Hifz Plan", text: "A structured memorization plan tailored to your level, goals, and availability." },
    { title: "Regular Revision", text: "Systematic review sessions help strengthen memorization and reduce forgetting." },
    { title: "Experienced Teachers", text: "Receive continuous guidance, motivation, and correction from qualified Quran teachers." },
    { title: "One-to-One Learning", text: "Study in private online lessons with individual attention and flexible scheduling." },
  ],
  learning: [
    { title: "New Memorization", text: "Memorize new verses step by step using a personalized plan that matches your pace and learning capacity." },
    { title: "Daily Revision", text: "Strengthen your memorization through regular revision sessions designed to improve long-term retention." },
    { title: "Accuracy & Fluency", text: "Recite your memorized portions with confidence while receiving continuous correction and guidance." },
    { title: "Progress Tracking", text: "Monitor your memorization journey through regular assessments and achievable milestones." },
    { title: "Personalized Guidance", text: "Receive one-to-one coaching and motivation from experienced Quran teachers throughout your Hifz journey." },
    { title: "Strong Hifz Foundation", text: "Build disciplined memorization habits that help you preserve your Hifz and continue progressing." },
  ],
  steps: [
    { title: "Free Assessment", text: "We evaluate your current memorization level, recitation, and learning goals." },
    { title: "Personal Hifz Plan", text: "Your teacher creates a plan based on your pace, availability, and long-term objectives." },
    { title: "Memorize & Revise", text: "Each lesson combines new memorization with structured revision to strengthen retention." },
    { title: "Track Your Progress", text: "Regular evaluations and feedback help you stay motivated and achieve steady progress." },
  ],
  schedule: "There are no fixed weekly lesson times. During your free assessment, your teacher will recommend a personalized schedule based on your memorization goals, availability, and learning pace. This flexible approach allows every student to progress consistently while balancing school, work, or family commitments.",
  price: "$100 / 10 Lessons",
  priceFeatures: [...commonPrice, "Personalized Hifz Plan", "New Memorization & Revision"],
  reasons: [
    { title: "Structured Hifz Method", text: "A clear system balances new memorization with regular revision for long-term retention." },
    { title: "Qualified Quran Teachers", text: "Experienced teachers guide, motivate, and monitor every stage of your journey." },
    { title: "Personalized Learning Plan", text: "Your Hifz plan is based on your level, goals, and available study time." },
    { title: "Regular Revision", text: "Consistent review strengthens memorization, reduces forgetting, and improves confidence." },
    { title: "Live One-to-One Lessons", text: "Private online lessons provide individual attention and immediate feedback." },
    { title: "Learn from Anywhere", text: "Flexible online scheduling fits your school, work, or family routine." },
  ],
  faqs: [
    { q: "Do I need to have memorized Quran before joining?", a: "No. The program is suitable for beginners and students who have already memorized parts of the Quran." },
    { q: "How much Quran will I memorize each week?", a: "The amount depends on your level, available study time, and learning goals. Your teacher creates a personalized plan." },
    { q: "Is revision included in the lessons?", a: "Yes. Every lesson includes structured revision alongside new memorization to strengthen retention." },
    { q: "How are students assessed?", a: "Teachers regularly assess memorization, accuracy, and revision progress to ensure steady improvement." },
    { q: "How do I begin?", a: "Book your FREE trial lesson. We'll assess your level, discuss your goals, and prepare a personalized Hifz plan." },
  ],
  ctaTitle: "Begin Your Quran Memorization Journey Today",
  ctaText: "Take the first step toward memorizing the Book of Allah with confidence and consistency. Our qualified teachers will guide you with a personalized plan, regular revision, and continuous support.",
};

export const arabicLanguage: ProgramContent = {
  eyebrow: "Arabic Language Program",
  title: "Learn Arabic with Confidence",
  intro: "Develop your Arabic language skills through personalized one-to-one online lessons designed for beginners and intermediate learners. Whether your goal is to understand the Quran, communicate confidently, or build a strong foundation in Arabic, our experienced teachers will guide you every step of the way.",
  assessment: "Every student begins with a FREE trial lesson, where we assess your current level, discuss your learning goals, and create a personalized study plan tailored to your needs.",
  overviewTitle: "Build a Strong Foundation in Arabic",
  overview: ["Our Arabic Language Program helps students develop practical language skills through personalized one-to-one online lessons. Whether you're learning for personal growth, academic studies, travel, or to better understand the Quran, we provide a structured path tailored to your goals.", "Every student begins with a free assessment lesson where we evaluate their current level, identify learning objectives, and create a personalized study plan that supports steady and enjoyable progress.", "Lessons combine speaking, listening, reading, and writing with interactive activities that help students build confidence and use Arabic in real-life situations."],
  benefits: [
    { title: "Personalized Learning Plan", text: "A customized curriculum designed around your level, interests, and learning goals." },
    { title: "Interactive Lessons", text: "Engaging one-to-one classes that encourage active participation and practical language use." },
    { title: "Qualified Teachers", text: "Experienced Arabic teachers provide clear explanations and continuous support." },
    { title: "Flexible Scheduling", text: "Choose lesson times that fit your daily routine and learn at a pace that works for you." },
  ],
  learning: [
    { title: "Speaking", text: "Build confidence through guided conversations, pronunciation practice, and real-life communication exercises." },
    { title: "Listening", text: "Improve your ability to understand spoken Arabic in everyday situations and classroom activities." },
    { title: "Reading", text: "Read Arabic words, sentences, and texts with increasing fluency while expanding vocabulary and comprehension." },
    { title: "Writing", text: "Write Arabic letters, words, and sentences accurately while developing proper spelling and grammar skills." },
    { title: "Vocabulary & Grammar", text: "Expand your vocabulary and understand essential grammar rules that help you communicate naturally." },
    { title: "Real-Life Communication", text: "Apply what you learn through practical examples and everyday conversations." },
  ],
  steps: [
    { title: "Free Assessment", text: "We evaluate your current Arabic level, discuss your goals, and recommend the best path." },
    { title: "Personal Study Plan", text: "Your teacher creates a plan based on your level, interests, and desired skills." },
    { title: "Live One-to-One Lessons", text: "Practice speaking, listening, reading, and writing through live practical activities." },
    { title: "Track Your Progress", text: "Regular feedback and assessments help you monitor improvement and achieve your goals." },
  ],
  schedule: "There are no fixed weekly lesson times. During your free assessment, your teacher will recommend a personalized schedule based on your availability, learning objectives, and pace. This flexible approach makes it easy to balance your Arabic studies with work, school, or family life.",
  price: "$100 / 10 Lessons",
  priceFeatures: [...commonPrice, "Speaking, Reading, Writing & Listening Practice"],
  reasons: [
    { title: "Qualified Arabic Teachers", text: "Experienced teachers provide clear explanations, practical exercises, and encouragement." },
    { title: "Personalized Learning Plans", text: "Every lesson is tailored to your level, objectives, and preferred pace." },
    { title: "Practical Communication", text: "Develop real-world speaking, listening, reading, and writing skills." },
    { title: "Live One-to-One Lessons", text: "Individual attention lets your teacher adapt every session to your needs." },
    { title: "Progress Tracking", text: "Regular feedback and assessments help you measure improvement and stay motivated." },
    { title: "Learn from Anywhere", text: "Study online worldwide with flexible scheduling that fits your life." },
  ],
  faqs: [
    { q: "Do I need any previous knowledge of Arabic?", a: "No. The program suits complete beginners as well as students who want to improve existing skills." },
    { q: "What language will the lessons be taught in?", a: "Teachers adapt the lesson language to your level. Beginners receive clear explanations, while advanced students are gradually immersed in Arabic." },
    { q: "Which skills will I develop?", a: "You will develop speaking, listening, reading, and writing while expanding vocabulary and understanding grammar." },
    { q: "Can I learn Arabic to better understand the Quran?", a: "Yes. Many students join to build a foundation that helps them understand the Quran and classical Islamic texts." },
    { q: "How do I get started?", a: "Book your FREE trial lesson. We'll assess your level, discuss your goals, and create a personalized plan." },
  ],
  ctaTitle: "Start Your Arabic Learning Journey Today",
  ctaText: "Whether your goal is to speak Arabic confidently, understand the Quran more deeply, or build a strong foundation in the language, our experienced teachers are here to support you every step of the way.",
};
