"use client";

import { useEffect, useMemo, useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { INDIVIDUAL_AREAS, type IndividualArea } from "@/lib/individual-lessons";

type Availability = { id: string; weekday: number; start_time: string; end_time: string; lesson_duration_minutes: number; buffer_minutes: number };
type Teacher = { id: string; full_name: string; availability: Availability[] };
type Choice = { availability_id: string; weekday: number; start_time: string; label: string };
const DAYS = ["Mondays", "Tuesdays", "Wednesdays", "Thursdays", "Fridays", "Saturdays", "Sundays"];
const input = "w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30";
function minutes(value: string) { const [h,m] = value.slice(0,5).split(":").map(Number); return h*60+m; }
function clock(value: number) { return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`; }

export default function IndividualLessonsPage() {
  const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [form, setForm] = useState({ teacher_id: "", area: "quran_reading" as IndividualArea, name: "", email: "", phone: "", address: "", postal_code: "", city: "", experience: "", alternative_time_request: "", requested_sessions_per_week: "1" });
  const [selected, setSelected] = useState<Choice[]>([]);
  const [message, setMessage] = useState(""); const [sending, setSending] = useState(false);
  useEffect(() => { fetch("/api/individual/teachers").then(r=>r.json()).then(setTeachers).catch(()=>setMessage("Could not load teachers.")); }, []);
  const teacher = teachers.find(t=>t.id===form.teacher_id);
  const choices = useMemo(() => (teacher?.availability ?? []).flatMap(a => { const out: Choice[]=[]; const end=minutes(a.end_time); for(let t=minutes(a.start_time); t+a.lesson_duration_minutes<=end; t += a.lesson_duration_minutes+a.buffer_minutes) out.push({availability_id:a.id,weekday:a.weekday,start_time:clock(t),label:`${DAYS[a.weekday-1]} ${clock(t)} (${a.lesson_duration_minutes} min)`}); return out; }), [teacher]);
  function toggle(c: Choice) { setSelected(current => current.some(x=>x.availability_id===c.availability_id&&x.start_time===c.start_time) ? current.filter(x=>!(x.availability_id===c.availability_id&&x.start_time===c.start_time)) : current.length < 3 ? [...current,c] : current); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setSending(true); setMessage(""); const r=await fetch("/api/individual/applications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,requested_sessions_per_week:Number(form.requested_sessions_per_week),preferences:selected})}); const d=await r.json(); setMessage(r.ok?"Thank you! Your application has been sent to the teacher for review.":d.error); if(r.ok)setSelected([]); setSending(false); }
  return <><Navbar/><main className="bg-[#faf9f6] min-h-screen py-14"><div className="max-w-4xl mx-auto px-4"><div className="text-center mb-10"><h1 className="text-3xl font-bold text-primary">Individual lessons</h1><p className="text-gray-500 mt-3">Choose a teacher and suggest up to three recurring weekly times. Lessons are free for now and no payment is taken.</p></div><form onSubmit={submit} className="bg-white rounded-2xl border p-6 sm:p-8 space-y-7">
    {message&&<div className="rounded-xl bg-amber-50 p-4 text-sm">{message}</div>}
    <section className="grid sm:grid-cols-2 gap-4"><label className="text-sm font-semibold">Area<select className={`${input} mt-1`} value={form.area} onChange={e=>setForm({...form,area:e.target.value as IndividualArea})}>{Object.entries(INDIVIDUAL_AREAS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Teacher<select required className={`${input} mt-1`} value={form.teacher_id} onChange={e=>{setForm({...form,teacher_id:e.target.value});setSelected([])}}><option value="">Choose teacher</option>{teachers.map(t=><option value={t.id} key={t.id}>{t.full_name}</option>)}</select></label></section>
    {teacher&&<section><div className="flex justify-between gap-3"><div><h2 className="font-semibold">Preferred weekly times</h2><p className="text-xs text-gray-500">Times are shown in Stockholm time. Choose up to 3.</p></div><label className="text-sm">Lessons/week<select className="ml-2 border rounded-lg p-1.5" value={form.requested_sessions_per_week} onChange={e=>setForm({...form,requested_sessions_per_week:e.target.value})}>{[1,2,3,4,5,6,7].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-4">{choices.map(c=>{const active=selected.some(x=>x.availability_id===c.availability_id&&x.start_time===c.start_time);return <button type="button" key={`${c.availability_id}-${c.start_time}`} onClick={()=>toggle(c)} className={`rounded-lg border p-3 text-sm text-left ${active?"text-white":"hover:bg-gray-50"}`} style={active?{background:"var(--primary)"}:{}}>{c.label}</button>})}</div>{choices.length===0&&<p className="text-sm text-gray-400 mt-3">This teacher has not published any available times yet. Ask for another time below.</p>}<textarea className={`${input} mt-4`} rows={3} placeholder="Ask for another time or describe scheduling needs" value={form.alternative_time_request} onChange={e=>setForm({...form,alternative_time_request:e.target.value})}/></section>}
    <section><h2 className="font-semibold mb-3">Your details</h2><div className="grid sm:grid-cols-2 gap-4"><input required className={input} placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" className={input} placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required className={input} placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input required className={input} placeholder="Street address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><input required className={input} placeholder="Postcode" value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})}/><input required className={input} placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><textarea className={`${input} sm:col-span-2`} rows={3} placeholder="Previous experience and goals" value={form.experience} onChange={e=>setForm({...form,experience:e.target.value})}/></div></section><button disabled={sending} className="w-full rounded-lg py-3 text-white font-semibold disabled:opacity-50" style={{background:"var(--accent)"}}>{sending?"Sending…":"Send application"}</button>
  </form></div></main><Footer/></>;
}
